from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from .model import (
    ToolsmithError,
    add_field,
    atomic_write,
    dump_data,
    file_fingerprint,
    iter_fields,
    load_data,
    stable_fingerprint,
    validate_contract,
    validate_field,
)

GENERATED_MARKER = "Generated by coferlandia-config-toolsmith. Do not edit manually."
DOC_NAMES = (
    "CONFIG-AGENT-HANDBOOK.md",
    "CONFIG-CLI-REFERENCE.md",
    "CONFIG-FIELD-REFERENCE.md",
    "CONFIG-INTENT-CATALOG.md",
    "CONFIG-RECIPES.md",
    "CONFIG-SAFETY.md",
    "CONFIG-TROUBLESHOOTING.md",
)


def inspect_contract(contract: dict[str, Any]) -> dict[str, Any]:
    fields = list(iter_fields(contract))
    adapters: dict[str, int] = {}
    for _, field in fields:
        adapter = field.get("binding", {}).get("adapter", "unknown")
        adapters[adapter] = adapters.get(adapter, 0) + 1
    return {
        "schema_version": contract.get("schema_version"),
        "application": contract.get("application", {}).get("name"),
        "command": contract.get("application", {}).get("command"),
        "modules": len(contract.get("modules", [])),
        "fields": len(fields),
        "writable": sum(1 for _, field in fields if field.get("writable")),
        "secrets": sum(1 for _, field in fields if field.get("secret")),
        "adapters": adapters,
        "contract_fingerprint": stable_fingerprint(contract),
    }


def load_candidates(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"schema_version": 1, "candidates": []}
    data = load_data(path)
    if not isinstance(data, dict) or not isinstance(data.get("candidates", []), list):
        raise ToolsmithError("candidate ledger must contain a candidates list", code=3)
    data.setdefault("schema_version", 1)
    return data


def load_decisions(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"schema_version": 1, "decisions": []}
    data = load_data(path)
    if not isinstance(data, dict) or not isinstance(data.get("decisions", []), list):
        raise ToolsmithError("decision ledger must contain a decisions list", code=3)
    data.setdefault("schema_version", 1)
    return data


def find_candidate(ledger: dict[str, Any], candidate_id: str) -> dict[str, Any]:
    for candidate in ledger.get("candidates", []):
        if candidate.get("id") == candidate_id:
            return candidate
    raise ToolsmithError(f"unknown candidate: {candidate_id}", code=2)


def decide_candidate(
    *,
    action: str,
    candidate_id: str,
    candidates_path: Path,
    contract_path: Path,
    decisions_path: Path,
    expected_fingerprint: str | None,
    dry_run: bool,
) -> dict[str, Any]:
    ledger = load_candidates(candidates_path)
    candidate = find_candidate(ledger, candidate_id)
    current_status = candidate.get("status", "pending")
    allowed_source = {"pending", "deferred", "approved"}
    if current_status not in allowed_source:
        raise ToolsmithError(
            f"candidate {candidate_id} is not reviewable from status {current_status}", code=5
        )
    source_fingerprint = candidate.get("source_fingerprint")
    if source_fingerprint and expected_fingerprint != source_fingerprint:
        candidate["status"] = "stale"
        if not dry_run:
            atomic_write(candidates_path, dump_data(ledger))
        raise ToolsmithError(
            f"candidate {candidate_id} is stale: expected fingerprint {source_fingerprint}",
            code=3,
        )

    contract = load_data(contract_path)
    result = validate_contract(contract)
    if not result.valid:
        raise ToolsmithError("contract is invalid before candidate decision", code=3, details=result.errors)
    decisions = load_decisions(decisions_path)

    status_by_action = {
        "approve": "implemented",
        "reject": "rejected",
        "defer": "deferred",
        "intentionally-unmanaged": "intentionally_unmanaged",
    }
    if action not in status_by_action:
        raise ToolsmithError(f"unsupported candidate action: {action}", code=2)

    changed_contract = False
    if action == "approve":
        proposed_field = candidate.get("proposed_field")
        module_name = candidate.get("proposed_module")
        if not isinstance(proposed_field, dict) or not isinstance(module_name, str):
            raise ToolsmithError(
                f"candidate {candidate_id} lacks proposed_field/proposed_module", code=3
            )
        field_result = validate_field(proposed_field, module_name=module_name)
        if not field_result.valid:
            raise ToolsmithError("proposed field is invalid", code=3, details=field_result.errors)
        existing = [field.get("key") for _, field in iter_fields(contract)]
        if proposed_field.get("key") not in existing:
            add_field(contract, proposed_field, module_name)
            changed_contract = True
        contract_result = validate_contract(contract)
        if not contract_result.valid:
            raise ToolsmithError(
                "contract would be invalid after approval", code=3, details=contract_result.errors
            )

    next_status = status_by_action[action]
    decision = {
        "candidate_id": candidate_id,
        "action": action,
        "source_fingerprint": source_fingerprint,
        "contract_fingerprint_before": stable_fingerprint(load_data(contract_path)),
        "contract_fingerprint_after": stable_fingerprint(contract),
    }
    already = any(
        item.get("candidate_id") == candidate_id and item.get("action") == action
        for item in decisions["decisions"]
    )
    if not already:
        decisions["decisions"].append(decision)
    candidate["status"] = next_status

    artifacts = []
    if not dry_run:
        if changed_contract:
            atomic_write(contract_path, dump_data(contract))
            artifacts.append({"path": str(contract_path), "action": "updated"})
        atomic_write(candidates_path, dump_data(ledger))
        atomic_write(decisions_path, dump_data(decisions))
        artifacts.extend(
            [
                {"path": str(candidates_path), "action": "updated"},
                {"path": str(decisions_path), "action": "updated"},
            ]
        )
    return {
        "candidate_id": candidate_id,
        "action": action,
        "status": next_status,
        "contract_changed": changed_contract,
        "dry_run": dry_run,
        "artifacts": artifacts,
    }


def _field_lines(contract: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    for module, field in iter_fields(contract):
        binding = field.get("binding", {})
        lines.extend(
            [
                f"## `{field['key']}`",
                "",
                field.get("description", ""),
                "",
                f"- Module: `{module['name']}`",
                f"- Type: `{field.get('type')}`",
                f"- Writable: `{str(bool(field.get('writable'))).lower()}`",
                f"- Secret: `{str(bool(field.get('secret'))).lower()}`",
                f"- Native adapter: `{binding.get('adapter')}`",
                f"- Native binding: `{json.dumps(binding, ensure_ascii=False, sort_keys=True)}`",
                f"- Validation: `{json.dumps(field.get('validation', {}), ensure_ascii=False, sort_keys=True)}`",
                f"- Effects: `{json.dumps(field.get('effects', {}), ensure_ascii=False, sort_keys=True)}`",
                "",
                "Inspect:",
                "",
                f"```bash\n<app> config get {field['key']} --json\n```",
                "",
            ]
        )
    return lines


def render_docs(contract: dict[str, Any]) -> dict[str, str]:
    app = contract["application"]
    command = app["command"]
    header = f"<!-- {GENERATED_MARKER} -->\n"
    fields = list(iter_fields(contract))
    module_rows = "\n".join(
        f"| `{module['name']}` | {module.get('description','')} | {len(module.get('fields', []))} |"
        for module in contract.get("modules", [])
    ) or "| *(none)* | | 0 |"
    handbook = header + f"""# Configuration Agent Handbook — {app['name']}

Use the standardized configuration CLI as the only supported interface for managed settings.
Do not edit managed native stores directly when an equivalent command exists.

## Mandatory agent workflow

1. Interpret the user's desired outcome.
2. Inspect capabilities and relevant modules.
3. Read live effective state.
4. Prepare or dry-run the smallest valid change set.
5. Explain warnings and operational effects.
6. Apply only with required authority.
7. Validate the live result and report activation/rollback.

Deterministic search is non-authoritative. A zero-result search means only that retrieval was
inconclusive. Before reporting a change unsupported, read this handbook completely and inspect
managed fields, pending candidates, intentionally unmanaged settings, read-only fields, and
unsupported adapters.

## Command root

```bash
{command} config capabilities --json
{command} config agent-context --all --json
```

## Modules

| Module | Description | Fields |
|---|---|---:|
{module_rows}

## Safety

- Inspect before mutation.
- Use `prepare-change` or `--dry-run` before apply.
- Never pass secrets as command-line values.
- Persisted and effective values may differ; trust live CLI output.
- Restart, migration, and downtime are separate approval boundaries.
"""
    cli_reference = header + f"""# Configuration CLI Reference — {app['name']}

```text
{command} setup [--quick|--reconfigure]
{command} config [<module>]
{command} config modules
{command} config describe <module-or-key>
{command} config get <key>
{command} config show [module]
{command} config set <key> <value> --dry-run|--confirm
{command} config unset <key> --dry-run|--confirm
{command} config validate [module]
{command} config capabilities
{command} config coverage
{command} config agent-context --all
{command} config prepare-change --set <key>=<value> --output <plan>
{command} config apply-plan --plan-file <plan> --confirm
```

All operational commands support `--json` where applicable. Diagnostics go to stderr. Mutations
must reject stale native state and report exact changed native artifacts.
"""
    field_reference = header + "# Configuration Field Reference\n\n" + "\n".join(_field_lines(contract))
    intent_sections: list[str] = [header + f"# Configuration Intent Catalog — {app['name']}\n"]
    recipe_sections: list[str] = [header + f"# Configuration Recipes — {app['name']}\n"]
    for module, field in fields:
        intents = field.get("user_intents", [])
        if intents:
            intent_sections.append(f"## {field['key']}\n")
            intent_sections.extend(f"- {intent}" for intent in intents)
            intent_sections.append(f"\nInspect with `{command} config describe {field['key']} --json`.\n")
        examples = field.get("examples", [])
        if examples:
            recipe_sections.append(f"## Change `{field['key']}`\n")
            for example in examples:
                recipe_sections.append(
                    f"User intent: {example.get('request','')}\n\n"
                    f"```bash\n{command} config prepare-change --set {field['key']}={json.dumps(example.get('value'))} --output change-plan.json --json\n"
                    f"{command} config apply-plan --plan-file change-plan.json --confirm --json\n"
                    f"{command} config validate {module['name']} --json\n```\n"
                )
    safety = header + f"""# Configuration Safety — {app['name']}

- Native project configuration remains authoritative.
- The static contract contains no current/effective/secret values.
- Never edit managed stores directly when the CLI supports the operation.
- Use stdin or the native provider for secrets.
- Treat warnings and activation effects as unresolved until evaluated.
- Do not cross restart, migration, downtime, or destructive boundaries without explicit authority.
- Reject stale plans and re-prepare from live state.
"""
    troubleshooting = header + f"""# Configuration Troubleshooting — {app['name']}

## Search returned no matches

Read `CONFIG-AGENT-HANDBOOK.md` completely and inspect coverage/candidates before concluding the
request is unsupported.

## Persisted value differs from effective value

Use `{command} config get <key> --json` to inspect the effective source and overrides. Write only to
an approved target that can affect the effective result.

## Plan is stale

Run `prepare-change` again. Do not force a plan over changed native state.

## Requested field is pending

Return the candidate id to `coferlandia-config-toolsmith` for explicit review. Do not bypass the
facade with a direct file edit.
"""
    return {
        "CONFIG-AGENT-HANDBOOK.md": handbook,
        "CONFIG-CLI-REFERENCE.md": cli_reference,
        "CONFIG-FIELD-REFERENCE.md": field_reference,
        "CONFIG-INTENT-CATALOG.md": "\n".join(intent_sections) + "\n",
        "CONFIG-RECIPES.md": "\n".join(recipe_sections) + "\n",
        "CONFIG-SAFETY.md": safety,
        "CONFIG-TROUBLESHOOTING.md": troubleshooting,
    }


def generate_docs(contract: dict[str, Any], output_dir: Path, *, dry_run: bool) -> dict[str, Any]:
    docs = render_docs(contract)
    artifacts = []
    for name, content in docs.items():
        path = output_dir / name
        action = "updated" if path.exists() else "created"
        if not dry_run:
            atomic_write(path, content)
        artifacts.append({"path": str(path), "action": action})
    return {"dry_run": dry_run, "artifacts": artifacts, "document_count": len(docs)}


def _skill_root() -> Path:
    return Path(__file__).resolve().parents[2]


def detect_platform(target_root: Path) -> str:
    if any(target_root.glob("*.sln")) or any(target_root.rglob("*.csproj")):
        return "dotnet"
    if (target_root / "pyproject.toml").exists() or (target_root / "setup.py").exists():
        return "python"
    return "fallback-python"


def generate_facade(
    contract: dict[str, Any], target_root: Path, platform: str, *, dry_run: bool
) -> dict[str, Any]:
    if platform == "auto":
        platform = detect_platform(target_root)
    command = contract["application"]["command"]
    contract_rel = Path(".coferlandia/config-toolsmith/contract.yaml")
    artifacts: list[dict[str, str]] = []
    templates = _skill_root() / "templates"

    contract_target = target_root / contract_rel
    contract_text = dump_data(contract)
    contract_existed = contract_target.exists()
    if not dry_run:
        atomic_write(contract_target, contract_text)
    artifacts.append(
        {"path": str(contract_target), "action": "updated" if contract_existed else "created"}
    )

    if platform in {"python", "fallback-python"}:
        template = (templates / "python-config-cli.py.tmpl").read_text(encoding="utf-8")
        source = template.replace("__APP_COMMAND__", command).replace(
            "__CONTRACT_PATH__", contract_rel.as_posix()
        )
        output = target_root / "scripts" / f"{command}-config-cli.py"
        output_existed = output.exists()
        if not dry_run:
            atomic_write(output, source)
        artifacts.append({"path": str(output), "action": "updated" if output_existed else "created"})
    elif platform == "dotnet":
        out_dir = target_root / "tools" / f"{command}-config"
        program = (templates / "dotnet" / "Program.cs.tmpl").read_text(encoding="utf-8")
        program = program.replace("__APP_COMMAND__", command).replace(
            "__CONTRACT_PATH__", contract_rel.as_posix()
        )
        project = (templates / "dotnet" / "ConfigCli.csproj.tmpl").read_text(encoding="utf-8")
        for path, source in ((out_dir / "Program.cs", program), (out_dir / f"{command}-config.csproj", project)):
            existed = path.exists()
            if not dry_run:
                atomic_write(path, source)
            artifacts.append({"path": str(path), "action": "updated" if existed else "created"})
    else:
        raise ToolsmithError(f"unsupported generation platform: {platform}", code=2)
    return {"platform": platform, "dry_run": dry_run, "artifacts": artifacts}


def check_drift(contract: dict[str, Any], output_dir: Path) -> dict[str, Any]:
    expected = render_docs(contract)
    drift: list[dict[str, str]] = []
    for name, content in expected.items():
        path = output_dir / name
        if not path.exists():
            drift.append({"path": str(path), "reason": "missing"})
        elif path.read_text(encoding="utf-8") != content:
            drift.append({"path": str(path), "reason": "content_mismatch"})
    return {"drift": drift, "clean": not drift}


def self_check(repo: Path | None) -> dict[str, Any]:
    skill_root = _skill_root()
    required = [
        skill_root / "SKILL.md",
        skill_root / "templates" / "python-config-cli.py.tmpl",
        skill_root / "templates" / "dotnet" / "Program.cs.tmpl",
    ]
    missing = [str(path) for path in required if not path.exists()]
    result: dict[str, Any] = {"skill_root": str(skill_root), "missing": missing}
    if repo is not None:
        result["repo"] = str(repo.resolve())
        result["repo_exists"] = repo.exists()
    result["healthy"] = not missing and (repo is None or repo.exists())
    return result
